# netlify.toml

[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# Define environment variables for different contexts
[context.production.environment]
  NODE_ENV = "production"

# Fix: Correctly configured scheduled function
[functions."scheduled-mot-check"]
  schedule = "@hourly"

# Redirect all API requests to Netlify Functions - ensure this is working
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true # Force this redirect to always happen

# Additional explicit redirects for specific functions
[[redirects]]
  from = "/api/getMonitoredVehicles"
  to = "/.netlify/functions/getMonitoredVehicles"
  status = 200
  force = true

[[redirects]]
  from = "/api/getPendingNotifications*"
  to = "/.netlify/functions/getPendingNotifications:splat"
  status = 200
  force = true

# Redirect all other requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Define headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://history.mot.api.gov.uk https://login.microsoftonline.com; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; frame-src 'self'; object-src 'none';"

# Define headers for service worker
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"

# Set correct MIME types for JavaScript and CSS files
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

# Add cache control for API endpoints to prevent caching
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"